Repository 24LIKELION-CHAEUM/Frontend, pull requests merged in 2024-07, with the labels that each got.

#4 #1/로그인
  .vscode/extensions.json
  assets/check_activated.svg
  assets/check_unactivated.svg
  assets/보호자.png
  assets/시니어.png
  css/fonts.css
  css/fonts/PRETENDARD-BOLD.OTF
  css/fonts/PRETENDARD-MEDIUM.OTF
  css/fonts/PRETENDARD-REGULAR.OTF
  css/main.css
  css/signin/signin.css
  css/signup/signup_id.css
  css/signup/signup_name.css
  css/signup/signup_type.css
  html/main.html
  html/signin/signin.html
  html/signup/signup_id.html
  html/signup/signup_name.html
  html/signup/signup_type.html
  js/signin/signin.js
  js/signup/signup_id.js
  js/signup/signup_name.js
  js/signup/signup_type.js
Labels: 혜음, UI

#8 #7/네비게이션바
  assets/nav/nav_building_active.svg
  assets/nav/nav_building_inactive.svg
  assets/nav/nav_finger_active.svg
  assets/nav/nav_finger_inactive.svg
  assets/nav/nav_home_active.svg
  assets/nav/nav_home_inactive.svg
  assets/nav/nav_user_active.svg
  assets/nav/nav_user_inactive.svg
  css/nav.css
  html/click.html
  html/home.html
  html/main.html
  html/mypage.html
  html/signin/signin.html
  html/signup/signup_id.html
  html/signup/signup_name.html
  html/signup/signup_parent.html
  html/signup/signup_type.html
  html/welfare.html
  js/nav.js
  js/signup/signup_type.js
Labels: 혜음, UI, 기능

#10 #9/버튼 비활성화 수정
  html/signin/signin.html
  js/signin/signin.js
Labels: 혜음, UI

#12 #11/마이페이지
  assets/pencil.svg
  css/fonts.css
  css/fonts/PRETENDARD-SEMIBOLD.OTF
  css/mypage.css
  css/signin/signin.css
  css/signup/signup_id.css
  css/signup/signup_name.css
  css/signup/signup_parent.css
  css/signup/signup_type.css
  html/mypage.html
  js/mypage.js
Labels: 혜음, UI

#17 #14/홈
  assets/arrow_next.svg
  css/fonts.css
  css/home.css
  html/home.html
  js/home.js
Labels: 혜음, UI

#16 #15/알림
  assets/medecine.png
  css/alarm.css
  html/alarm.html
  js/alarm.js
Labels: 혜음, UI

#13 #3/회원가입시니어
  .DS_Store
  .github/ISSUE_TEMPLATE/issue---.md
  .github/pull_request_template.md
  assets/arrow_back.svg
  css/.DS_Store
  css/example.css
  css/seniorlogin.css
  html/seniorlogin.html
  img/back.png
  img/bottombar.svg
  img/check.svg
  img/front.png
  img/pill.png
  img/rice.png
  js/seniorlogin.js
Labels: 예은, UI

#19 #18/콕찌르기
  assets/click.svg
  assets/x.svg
  css/click.css
  html/parent/click.html
  html/senior/click.html
  js/click.js
  js/parent/click.js
  js/senior/click.js
Labels: 혜음, UI

#22 #20/홈 ui 업데이트
  assets/alarm.svg
  assets/background.png
  assets/home_graphic.png
  assets/home_smile.svg
  assets/home_task.svg
  assets/logo.png
  css/home.css
  html/parent/home.html
  html/parent/mypage.html
  html/senior/home.html
Labels: 혜음, UI

#25 #21/오늘의 감정
  assets/add_activated.svg
  assets/add_unactivated.svg
  assets/arrow_back.svg
  css/emotion.css
  html/senior/emotion.html
  html/senior/home.html
  js/senior/emotion.js
Labels: 혜음, UI

#27 #26/오늘의 할 일
  assets/default.png
  css/home.css
  css/todo.css
  html/parent/todo.html
  html/senior/home.html
  html/senior/todo.html
  js/parent/todo.js
  js/senior/todo.js
Labels: 혜음, UI

#31 #29/시니어회원가입
  css/fonts.css
  css/home.css
  css/seniorlogin.css
  css/signup/signup_meal.css
  css/signup/signup_mediation.css
  css/signup/signup_senior.css
  css/todo.css
  html/parent/alarm.html
  html/parent/home.html
  html/senior/alarm.html
  html/senior/home.html
  html/senior/todo.html
  html/seniorlogin.html
  html/signup/signup_id.html
  html/signup/signup_meal.html
  html/signup/signup_mediation.html
  html/signup/signup_name.html
  html/signup/signup_parent.html
  html/signup/signup_senior.html
  js/parent/home.js
  js/senior/home.js
  js/seniorlogin.js
  js/signup/signup_meal.js
  js/signup/signup_mediation.js
  js/signup/signup_name.js
  js/signup/signup_senior.js
  js/signup/signup_type.js
Labels: 혜음, UI, FIX

#33 #32/꿀팁
  assets/tip.png
  css/tip.css
  html/parent/home.html
  html/parent/tip.html
Labels: 혜음, UI

#35 #24/복지시설
  css/.DS_Store
  css/nav.css
  css/senior/welfare.css
  html/.DS_Store
  html/senior/welfare.html
  img/call.svg
  img/facility.svg
  img/위치.png
  img/위치.svg
  js/.DS_Store
  js/senior/welfare.js
Labels: 예은, UI

#36 #34/정리
  css/alarm.css
  css/click.css
  css/emotion.css
  css/home.css
  css/main.css
  css/mypage.css
  css/senior/welfare.css
  css/signin/signin.css
  css/signup/signup_id.css
  css/signup/signup_meal.css
  css/signup/signup_mediation.css
  css/signup/signup_name.css
  css/signup/signup_parent.css
  css/signup/signup_senior.css
  css/signup/signup_type.css
  css/tip.css
  css/todo.css
  html/parent/alarm.html
  html/parent/todo.html
  html/senior/alarm.html
  html/senior/todo.html
  js/parent/alarm.js
  js/parent/todo.js
  js/senior/alarm.js
  js/senior/todo.js
Labels: 혜음, FIX
